server:
  port: 8761
  servlet:
    context-path: /e-commerce

eureka:
#  server:
#    enable-self-preservation: false
#  dashboard:
#    enabled: true
#    path: /registry
#  instance:
#    hostname: 127.0.0.1
#    appname: orchestrator
#    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8794/e-commerce/eureka

spring:
#  main:
#    allow-bean-definition-overriding: true
#  autoconfigure:
#    exclude:
  application:
    name: orchestrator

zuul:
  prefix: /rest
  routes:
#    account:
#      path: /account/**
#      serviceId: accounts
    orders:
      path: /orders/**
      url: http://localhost:7777/
#      serviceId: orders
#      strip-prefix: false
#ribbon:
#  eureka:
#    enabled: false
#
#orders:
#  ribbon:
#    listOfServers: ${EUREKA_URI:http://localhost:8794/e-commerce/eureka}
#
#accounts:
#  ribbon:
#    listOfServers: http://localhost:8794/e-commerce/eureka

ribbon:
  eureka:
    enabled: false
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: '*'


