server:
  port: 8761
  servlet:
    context-path: /e-commerce

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8794/e-commerce/eureka

spring:
  application:
    name: orchestrator
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

zuul:
  prefix: /rest/api
  routes:
    accounts:
      path: /accounts/**
      serviceId: accounts-service
    orders:
      path: /orders/**
      serviceId: orders-service
    products:
      path: /products/**
      serviceId: products-service

management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: '*'


