server:
  port: 8794
  servlet:
    context-path: /e-commerce

eureka:
  server:
    enable-self-preservation: true
    number-of-replication-retries: 0
    renewal-percent-threshold: 0.50
  dashboard:
    enabled: true
    path: /registry
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: Discovery
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

