server:
  port: 8794
  servlet:
    context-path: /e-commerce

eureka:
  server:
    enable-self-preservation: false
  dashboard:
    enabled: true
    path: /registry
  instance:
    appname: Xavi
  client:
    register-with-eureka: false
    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://localhost:8794/e-commerce/eureka/
