spring:
  application:
    name: orders

server:
  port: 7777
  servlet:
    context-path: /order-service

datasource:
  props:
    hostname: localhost
    port: 3306
    database: 'e_comm'
    username: 'demo_user'
    password: 'demo_pass'
    min: 1
    max: 10