spring:
  application:
    name: orders-service

server:
  port: 7777
  servlet:
    context-path: /order-service

datasource:
  props:
    hostname: localhost
    port: 3306
    database: 'e_comm'
    username: 'demo_user'
    password: 'demo_pass'
    min: 1
    max: 10

tables:
  productsTable: products
  ordersTable: orders
  orderStatusTable: order_status
  deliveryAddressTable: del_address
  usersTable: users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8794/e-commerce/eureka
  instance:
    metadata-map:
      context-path: ${server.servlet.context-path}
    prefer-ip-address: true
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    status-page-url-path: ${server.servlet.context-path}/actuator/status
