server:
  port: 4880
  servlet:
    context-path: /accounts-service

datasource:
  props:
    hostname: localhost
    port: 3306
    database: 'e_comm'
    username: 'demo_user'
    password: 'demo_pass'
    min: 1
    max: 10

tables:
  productsTable: products
  ordersTable: orders
  orderStatusTable: order_status
  deliveryAddressTable: del_address
  usersTable: users

#eureka:
#  instance:
#    status-page-url: http://localhost:${server.port}/actuator/info
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8794/e-commerce/eureka/

spring:
  application:
    name: accounts




