spring:
  application:
    name: common-utils

datasource:
  props:
    hostname: localhost
    port: 3306
    database: 'e_comm'
    username: 'demo_user'
    password: 'demo_pass'
    min: 1
    max: 10

tables:
  productsTable: products
  ordersTable: orders
  orderStatusTable: order_status
  deliveryAddressTable: del_address
  usersTable: users