server:
  port: 4881
  servlet:
    context-path: /products-service

spring:
  application:
    name: products-service

datasource:
  props:
    hostname: localhost
    port: 3306
    database: 'e_comm'
    username: 'demo_user'
    password: 'demo_pass'
    min: 1
    max: 10

tables:
  productsTable: products
  ordersTable: orders
  orderStatusTable: order_status
  deliveryAddressTable: del_address
  usersTable: users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8794/e-commerce/eureka
  instance:
    metadata-map:
      context-path: ${server.servlet.context-path}
      service-path: /products
    prefer-ip-address: true
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 20
logging:
  level:
    org.springframework: debug


